
# default: &default

#development:
#  # <<: *default
#  adapter: postgresql
#  encoding: unicode
#  host: <%#= ENV['SCOMCAT_POSTGRES_HOST'] %>
#  username: <%#= ENV['SCOMCAT_POSTGRES_USER'] %>
#  pool: 5
#  database: <%#= ENV['SCOMCAT_POSTGRES_DB'] %>
#  password: <%#= ENV['SCOMCAT_POSTGRES_PASSWORD'] %>

development:
  # <<: *default
  database: db/development.sqlite3
  adapter: sqlite3
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  timeout: 5000

test:
  # <<: *default
  database: db/test.sqlite3
  adapter: sqlite3
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  timeout: 5000

#production:
#  # <<: *default
#  adapter: postgresql
#  encoding: unicode
#  host: <%#= ENV['SCOMCAT_POSTGRES_HOST'] %>
#  username: <%#= ENV['SCOMCAT_POSTGRES_USER'] %>
#  pool: 5
#  database: <%#= ENV['SCOMCAT_POSTGRES_DB'] %>
#  password: <%#= ENV['SCOMCAT_POSTGRES_PASSWORD'] %>

production:
  # <<: *default
  database: db/development.sqlite3
  adapter: sqlite3
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  timeout: 5000