default: &default
  adapter: postgresql
  encoding: unicode
  host: <%= ENV['SCOMCAT_POSTGRES_HOST'] %>
  username: <%= ENV['SCOMCAT_POSTGRES_USER'] %>
  password: <%= ENV['SCOMCAT_POSTGRES_PASSWORD'] %>
  pool: 5

development:
  <<: *default
  database: scomcat_development

test:
  <<: *default
  database: scomcat_test

production:
  <<: *default
  database: <%= ENV['SCOMCAT_POSTGRES_DB'] %>

